connector.name=iceberg
iceberg.catalog.type=rest

# Iceberg REST endpoint de Nessie
iceberg.rest-catalog.uri=http://nessie:19120/iceberg

# (Opcional) lo puedes dejar si quieres tener un “root” claro
iceberg.rest-catalog.warehouse=s3://lakehouse/warehouse

# S3 nativo de Trino hacia MinIO
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=${ENV:MINIO_ROOT_USER}
s3.aws-secret-key=${ENV:MINIO_ROOT_PASSWORD}
