FROM apache/airflow:2.10.3-python3.11

USER root

RUN apt-get update && apt-get install -y \
    poppler-utils \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN apt-get update && apt-get install -y \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install acryl-datahub-airflow-plugin
RUN pip install --no-cache-dir --upgrade \
    google-api-python-client \
    google-auth-httplib2 \
    google-auth-oauthlib \
    boto3 \
    pyspark==3.5.1 \
    requests \
    pandas \
    botocore \
    pyarrow \
    psycopg2-binary

USER airflow