FROM public.ecr.aws/bitnami/spark:3.5.3
USER root

RUN install_packages curl poppler-utils && \
    /opt/bitnami/python/bin/pip install --no-cache-dir \
        jupyterlab notebook \
        boto3 pandas pyarrow \
        pdfplumber pikepdf \
        pdf2image pytesseract pillow \
        qdrant-client

RUN mkdir -p /opt/bitnami/spark/jars-extra && \
    curl -fL -o /opt/bitnami/spark/jars-extra/iceberg-spark-runtime-3.5_2.12-1.6.1.jar \
      https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.6.1/iceberg-spark-runtime-3.5_2.12-1.6.1.jar && \
    curl -fL -o /opt/bitnami/spark/jars-extra/hadoop-aws-3.3.4.jar \
      https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -fL -o /opt/bitnami/spark/jars-extra/aws-java-sdk-bundle-1.12.262.jar \
      https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

RUN mkdir -p /notebooks /root/.jupyter


COPY jupyter-setup.py /tmp/jupyter-setup.py
RUN /opt/bitnami/python/bin/python3 /tmp/jupyter-setup.py
RUN ls /opt/bitnami/spark/python/lib/

ENV PYTHONPATH=/opt/bitnami/spark/python:/opt/bitnami/spark/python/lib/py4j-0.10.9.7-src.zip
ENV SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/jars-extra/*
ENV PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
ENV PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python3

WORKDIR /notebooks

ENTRYPOINT []
CMD ["/opt/bitnami/python/bin/jupyter", "lab", \
     "--ip=0.0.0.0", \
     "--no-browser", \
     "--allow-root", \
     "--config=/root/.jupyter/jupyter_server_config.py"]