FROM apache/airflow:2.10.3-python3.11

USER root

RUN apt-get update && apt-get install -y \
    poppler-utils \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

ARG AIRFLOW_VERSION=2.10.3
ARG PYTHON_VERSION=3.11
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN pip install --no-cache-dir \
    --constraint "${CONSTRAINT_URL}" \
    apache-airflow-providers-trino \
    qdrant-client \
    google-api-python-client \
    google-auth-httplib2 \
    google-auth-oauthlib \
    boto3 \
    pyspark \
    requests \
    pdfplumber \
    pytesseract \
    pikepdf \
    pandas \
    botocore \
    pyarrow \
    psycopg2-binary